package com.fc.test.model.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TSysUserVaccinationInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public TSysUserVaccinationInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameIsNull() {
            addCriterion("vaccination_name is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameIsNotNull() {
            addCriterion("vaccination_name is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameEqualTo(String value) {
            addCriterion("vaccination_name =", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameNotEqualTo(String value) {
            addCriterion("vaccination_name <>", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameGreaterThan(String value) {
            addCriterion("vaccination_name >", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_name >=", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameLessThan(String value) {
            addCriterion("vaccination_name <", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameLessThanOrEqualTo(String value) {
            addCriterion("vaccination_name <=", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameLike(String value) {
            addCriterion("vaccination_name like", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameNotLike(String value) {
            addCriterion("vaccination_name not like", value, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameIn(List<String> values) {
            addCriterion("vaccination_name in", values, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameNotIn(List<String> values) {
            addCriterion("vaccination_name not in", values, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameBetween(String value1, String value2) {
            addCriterion("vaccination_name between", value1, value2, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationNameNotBetween(String value1, String value2) {
            addCriterion("vaccination_name not between", value1, value2, "vaccinationName");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdIsNull() {
            addCriterion("vaccination_user_id is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdIsNotNull() {
            addCriterion("vaccination_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdEqualTo(String value) {
            addCriterion("vaccination_user_id =", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNotEqualTo(String value) {
            addCriterion("vaccination_user_id <>", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdGreaterThan(String value) {
            addCriterion("vaccination_user_id >", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_user_id >=", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdLessThan(String value) {
            addCriterion("vaccination_user_id <", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdLessThanOrEqualTo(String value) {
            addCriterion("vaccination_user_id <=", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdLike(String value) {
            addCriterion("vaccination_user_id like", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNotLike(String value) {
            addCriterion("vaccination_user_id not like", value, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdIn(List<String> values) {
            addCriterion("vaccination_user_id in", values, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNotIn(List<String> values) {
            addCriterion("vaccination_user_id not in", values, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdBetween(String value1, String value2) {
            addCriterion("vaccination_user_id between", value1, value2, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNotBetween(String value1, String value2) {
            addCriterion("vaccination_user_id not between", value1, value2, "vaccinationUserId");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameIsNull() {
            addCriterion("vaccination_user_nickname is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameIsNotNull() {
            addCriterion("vaccination_user_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameEqualTo(String value) {
            addCriterion("vaccination_user_nickname =", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameNotEqualTo(String value) {
            addCriterion("vaccination_user_nickname <>", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameGreaterThan(String value) {
            addCriterion("vaccination_user_nickname >", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_user_nickname >=", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameLessThan(String value) {
            addCriterion("vaccination_user_nickname <", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameLessThanOrEqualTo(String value) {
            addCriterion("vaccination_user_nickname <=", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameLike(String value) {
            addCriterion("vaccination_user_nickname like", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameNotLike(String value) {
            addCriterion("vaccination_user_nickname not like", value, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameIn(List<String> values) {
            addCriterion("vaccination_user_nickname in", values, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameNotIn(List<String> values) {
            addCriterion("vaccination_user_nickname not in", values, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameBetween(String value1, String value2) {
            addCriterion("vaccination_user_nickname between", value1, value2, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserNicknameNotBetween(String value1, String value2) {
            addCriterion("vaccination_user_nickname not between", value1, value2, "vaccinationUserNickname");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberIsNull() {
            addCriterion("vaccination_user_id_number is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberIsNotNull() {
            addCriterion("vaccination_user_id_number is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberEqualTo(String value) {
            addCriterion("vaccination_user_id_number =", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberNotEqualTo(String value) {
            addCriterion("vaccination_user_id_number <>", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberGreaterThan(String value) {
            addCriterion("vaccination_user_id_number >", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_user_id_number >=", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberLessThan(String value) {
            addCriterion("vaccination_user_id_number <", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberLessThanOrEqualTo(String value) {
            addCriterion("vaccination_user_id_number <=", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberLike(String value) {
            addCriterion("vaccination_user_id_number like", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberNotLike(String value) {
            addCriterion("vaccination_user_id_number not like", value, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberIn(List<String> values) {
            addCriterion("vaccination_user_id_number in", values, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberNotIn(List<String> values) {
            addCriterion("vaccination_user_id_number not in", values, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberBetween(String value1, String value2) {
            addCriterion("vaccination_user_id_number between", value1, value2, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationUserIdNumberNotBetween(String value1, String value2) {
            addCriterion("vaccination_user_id_number not between", value1, value2, "vaccinationUserIdNumber");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateIsNull() {
            addCriterion("vaccination_date is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateIsNotNull() {
            addCriterion("vaccination_date is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateEqualTo(Date value) {
            addCriterionForJDBCDate("vaccination_date =", value, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("vaccination_date <>", value, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateGreaterThan(Date value) {
            addCriterionForJDBCDate("vaccination_date >", value, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vaccination_date >=", value, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateLessThan(Date value) {
            addCriterionForJDBCDate("vaccination_date <", value, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vaccination_date <=", value, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateIn(List<Date> values) {
            addCriterionForJDBCDate("vaccination_date in", values, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("vaccination_date not in", values, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vaccination_date between", value1, value2, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vaccination_date not between", value1, value2, "vaccinationDate");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountIsNull() {
            addCriterion("vaccination_amount is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountIsNotNull() {
            addCriterion("vaccination_amount is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountEqualTo(String value) {
            addCriterion("vaccination_amount =", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountNotEqualTo(String value) {
            addCriterion("vaccination_amount <>", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountGreaterThan(String value) {
            addCriterion("vaccination_amount >", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_amount >=", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountLessThan(String value) {
            addCriterion("vaccination_amount <", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountLessThanOrEqualTo(String value) {
            addCriterion("vaccination_amount <=", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountLike(String value) {
            addCriterion("vaccination_amount like", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountNotLike(String value) {
            addCriterion("vaccination_amount not like", value, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountIn(List<String> values) {
            addCriterion("vaccination_amount in", values, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountNotIn(List<String> values) {
            addCriterion("vaccination_amount not in", values, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountBetween(String value1, String value2) {
            addCriterion("vaccination_amount between", value1, value2, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationAmountNotBetween(String value1, String value2) {
            addCriterion("vaccination_amount not between", value1, value2, "vaccinationAmount");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceIsNull() {
            addCriterion("vaccination_place is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceIsNotNull() {
            addCriterion("vaccination_place is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceEqualTo(String value) {
            addCriterion("vaccination_place =", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceNotEqualTo(String value) {
            addCriterion("vaccination_place <>", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceGreaterThan(String value) {
            addCriterion("vaccination_place >", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_place >=", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceLessThan(String value) {
            addCriterion("vaccination_place <", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceLessThanOrEqualTo(String value) {
            addCriterion("vaccination_place <=", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceLike(String value) {
            addCriterion("vaccination_place like", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceNotLike(String value) {
            addCriterion("vaccination_place not like", value, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceIn(List<String> values) {
            addCriterion("vaccination_place in", values, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceNotIn(List<String> values) {
            addCriterion("vaccination_place not in", values, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceBetween(String value1, String value2) {
            addCriterion("vaccination_place between", value1, value2, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationPlaceNotBetween(String value1, String value2) {
            addCriterion("vaccination_place not between", value1, value2, "vaccinationPlace");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalIsNull() {
            addCriterion("vaccination_hospital is null");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalIsNotNull() {
            addCriterion("vaccination_hospital is not null");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalEqualTo(String value) {
            addCriterion("vaccination_hospital =", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalNotEqualTo(String value) {
            addCriterion("vaccination_hospital <>", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalGreaterThan(String value) {
            addCriterion("vaccination_hospital >", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalGreaterThanOrEqualTo(String value) {
            addCriterion("vaccination_hospital >=", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalLessThan(String value) {
            addCriterion("vaccination_hospital <", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalLessThanOrEqualTo(String value) {
            addCriterion("vaccination_hospital <=", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalLike(String value) {
            addCriterion("vaccination_hospital like", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalNotLike(String value) {
            addCriterion("vaccination_hospital not like", value, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalIn(List<String> values) {
            addCriterion("vaccination_hospital in", values, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalNotIn(List<String> values) {
            addCriterion("vaccination_hospital not in", values, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalBetween(String value1, String value2) {
            addCriterion("vaccination_hospital between", value1, value2, "vaccinationHospital");
            return (Criteria) this;
        }

        public Criteria andVaccinationHospitalNotBetween(String value1, String value2) {
            addCriterion("vaccination_hospital not between", value1, value2, "vaccinationHospital");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}