package com.fc.test.model.auto;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class TSysUserVaccinationInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_name
     *
     * @mbg.generated
     */
    private String vaccinationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_user_id
     *
     * @mbg.generated
     */
    private String vaccinationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_user_nickname
     *
     * @mbg.generated
     */
    private String vaccinationUserNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_user_id_number
     *
     * @mbg.generated
     */
    private String vaccinationUserIdNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",locale = "zh", timezone = "GMT+8")
    private String vaccinationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_amount
     *
     * @mbg.generated
     */
    private String vaccinationAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_place
     *
     * @mbg.generated
     */
    private String vaccinationPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_vaccination_info.vaccination_hospital
     *
     * @mbg.generated
     */
    private String vaccinationHospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user_vaccination_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public TSysUserVaccinationInfo(String id, String vaccinationName, String vaccinationUserId, String vaccinationUserNickname, String vaccinationUserIdNumber, String vaccinationDate, String vaccinationAmount, String vaccinationPlace, String vaccinationHospital) {
        this.id = id;
        this.vaccinationName = vaccinationName;
        this.vaccinationUserId = vaccinationUserId;
        this.vaccinationUserNickname = vaccinationUserNickname;
        this.vaccinationUserIdNumber = vaccinationUserIdNumber;
        this.vaccinationDate = vaccinationDate;
        this.vaccinationAmount = vaccinationAmount;
        this.vaccinationPlace = vaccinationPlace;
        this.vaccinationHospital = vaccinationHospital;
    }

    public TSysUserVaccinationInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.id
     *
     * @return the value of t_sys_user_vaccination_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.id
     *
     * @param id the value for t_sys_user_vaccination_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_name
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_name
     *
     * @mbg.generated
     */
    public String getVaccinationName() {
        return vaccinationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_name
     *
     * @param vaccinationName the value for t_sys_user_vaccination_info.vaccination_name
     *
     * @mbg.generated
     */
    public void setVaccinationName(String vaccinationName) {
        this.vaccinationName = vaccinationName == null ? null : vaccinationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_user_id
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_user_id
     *
     * @mbg.generated
     */
    public String getVaccinationUserId() {
        return vaccinationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_user_id
     *
     * @param vaccinationUserId the value for t_sys_user_vaccination_info.vaccination_user_id
     *
     * @mbg.generated
     */
    public void setVaccinationUserId(String vaccinationUserId) {
        this.vaccinationUserId = vaccinationUserId == null ? null : vaccinationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_user_nickname
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_user_nickname
     *
     * @mbg.generated
     */
    public String getVaccinationUserNickname() {
        return vaccinationUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_user_nickname
     *
     * @param vaccinationUserNickname the value for t_sys_user_vaccination_info.vaccination_user_nickname
     *
     * @mbg.generated
     */
    public void setVaccinationUserNickname(String vaccinationUserNickname) {
        this.vaccinationUserNickname = vaccinationUserNickname == null ? null : vaccinationUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_user_id_number
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_user_id_number
     *
     * @mbg.generated
     */
    public String getVaccinationUserIdNumber() {
        return vaccinationUserIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_user_id_number
     *
     * @param vaccinationUserIdNumber the value for t_sys_user_vaccination_info.vaccination_user_id_number
     *
     * @mbg.generated
     */
    public void setVaccinationUserIdNumber(String vaccinationUserIdNumber) {
        this.vaccinationUserIdNumber = vaccinationUserIdNumber == null ? null : vaccinationUserIdNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_date
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_date
     *
     * @mbg.generated
     */
    public String getVaccinationDate() {
        return vaccinationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_date
     *
     * @param vaccinationDate the value for t_sys_user_vaccination_info.vaccination_date
     *
     * @mbg.generated
     */
    public void setVaccinationDate(String vaccinationDate) {
        this.vaccinationDate = vaccinationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_amount
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_amount
     *
     * @mbg.generated
     */
    public String getVaccinationAmount() {
        return vaccinationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_amount
     *
     * @param vaccinationAmount the value for t_sys_user_vaccination_info.vaccination_amount
     *
     * @mbg.generated
     */
    public void setVaccinationAmount(String vaccinationAmount) {
        this.vaccinationAmount = vaccinationAmount == null ? null : vaccinationAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_place
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_place
     *
     * @mbg.generated
     */
    public String getVaccinationPlace() {
        return vaccinationPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_place
     *
     * @param vaccinationPlace the value for t_sys_user_vaccination_info.vaccination_place
     *
     * @mbg.generated
     */
    public void setVaccinationPlace(String vaccinationPlace) {
        this.vaccinationPlace = vaccinationPlace == null ? null : vaccinationPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_vaccination_info.vaccination_hospital
     *
     * @return the value of t_sys_user_vaccination_info.vaccination_hospital
     *
     * @mbg.generated
     */
    public String getVaccinationHospital() {
        return vaccinationHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_vaccination_info.vaccination_hospital
     *
     * @param vaccinationHospital the value for t_sys_user_vaccination_info.vaccination_hospital
     *
     * @mbg.generated
     */
    public void setVaccinationHospital(String vaccinationHospital) {
        this.vaccinationHospital = vaccinationHospital == null ? null : vaccinationHospital.trim();
    }
}