package com.fc.test.model.auto;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class TSysVaccineInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.vaccine_name
     *
     * @mbg.generated
     */
    private String vaccineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.approval_number
     *
     * @mbg.generated
     */
    private String approvalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.production_number
     *
     * @mbg.generated
     */
    private String productionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.production_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",locale = "zh", timezone = "GMT+8")
    private String productionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.effective_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",locale = "zh", timezone = "GMT+8")
    private String effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.factory_name
     *
     * @mbg.generated
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_vaccine_info.inventory
     *
     * @mbg.generated
     */
    private String inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public TSysVaccineInfo(String id, String vaccineName, String approvalNumber, String productionNumber, String productionDate, String effectiveDate, String factoryName, String inventory) {
        this.id = id;
        this.vaccineName = vaccineName;
        this.approvalNumber = approvalNumber;
        this.productionNumber = productionNumber;
        this.productionDate = productionDate;
        this.effectiveDate = effectiveDate;
        this.factoryName = factoryName;
        this.inventory = inventory;
    }
    public TSysVaccineInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.id
     *
     * @return the value of t_sys_vaccine_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.id
     *
     * @param id the value for t_sys_vaccine_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.vaccine_name
     *
     * @return the value of t_sys_vaccine_info.vaccine_name
     *
     * @mbg.generated
     */
    public String getVaccineName() {
        return vaccineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.vaccine_name
     *
     * @param vaccineName the value for t_sys_vaccine_info.vaccine_name
     *
     * @mbg.generated
     */
    public void setVaccineName(String vaccineName) {
        this.vaccineName = vaccineName == null ? null : vaccineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.approval_number
     *
     * @return the value of t_sys_vaccine_info.approval_number
     *
     * @mbg.generated
     */
    public String getApprovalNumber() {
        return approvalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.approval_number
     *
     * @param approvalNumber the value for t_sys_vaccine_info.approval_number
     *
     * @mbg.generated
     */
    public void setApprovalNumber(String approvalNumber) {
        this.approvalNumber = approvalNumber == null ? null : approvalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.production_number
     *
     * @return the value of t_sys_vaccine_info.production_number
     *
     * @mbg.generated
     */
    public String getProductionNumber() {
        return productionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.production_number
     *
     * @param productionNumber the value for t_sys_vaccine_info.production_number
     *
     * @mbg.generated
     */
    public void setProductionNumber(String productionNumber) {
        this.productionNumber = productionNumber == null ? null : productionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.production_date
     *
     * @return the value of t_sys_vaccine_info.production_date
     *
     * @mbg.generated
     */
    public String getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.production_date
     *
     * @param productionDate the value for t_sys_vaccine_info.production_date
     *
     * @mbg.generated
     */
    public void setProductionDate(String productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.effective_date
     *
     * @return the value of t_sys_vaccine_info.effective_date
     *
     * @mbg.generated
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.effective_date
     *
     * @param effectiveDate the value for t_sys_vaccine_info.effective_date
     *
     * @mbg.generated
     */
    public void setEffectiveDate(String effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.factory_name
     *
     * @return the value of t_sys_vaccine_info.factory_name
     *
     * @mbg.generated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.factory_name
     *
     * @param factoryName the value for t_sys_vaccine_info.factory_name
     *
     * @mbg.generated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_vaccine_info.inventory
     *
     * @return the value of t_sys_vaccine_info.inventory
     *
     * @mbg.generated
     */
    public String getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_vaccine_info.inventory
     *
     * @param inventory the value for t_sys_vaccine_info.inventory
     *
     * @mbg.generated
     */
    public void setInventory(String inventory) {
        this.inventory = inventory == null ? null : inventory.trim();
    }
}