package com.fc.test.mapper.auto;

import com.fc.test.model.auto.TSysVaccineInfo;
import com.fc.test.model.auto.TSysVaccineInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysVaccineInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    long countByExample(TSysVaccineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int deleteByExample(TSysVaccineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int insert(TSysVaccineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int insertSelective(TSysVaccineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    List<TSysVaccineInfo> selectByExample(TSysVaccineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    TSysVaccineInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSysVaccineInfo record, @Param("example") TSysVaccineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSysVaccineInfo record, @Param("example") TSysVaccineInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSysVaccineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_vaccine_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysVaccineInfo record);
}