package com.fc.test.mapper.auto;

import com.fc.test.model.auto.TSysConsumer;
import com.fc.test.model.auto.TSysConsumerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    long countByExample(TSysConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int deleteByExample(TSysConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int insert(TSysConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int insertSelective(TSysConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    List<TSysConsumer> selectByExample(TSysConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    TSysConsumer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSysConsumer record, @Param("example") TSysConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSysConsumer record, @Param("example") TSysConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSysConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_consumer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysConsumer record);
}